repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: detect-aws-credentials
    -   id: check-added-large-files
    -   id: check-json
    -   id: pretty-format-json
    -   id: fix-byte-order-marker
    -   id: fix-encoding-pragma
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
    -   id: check-shebang-scripts-are-executable
    -   id: check-docstring-first

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)

-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black

-   repo: git@github.com:humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
    -   id: autoflake
        args: ['--in-place', '--remove-all-unused-imports']

-   repo: https://gitlab.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
    -   id: flake8